# Generated by Django 4.2.2 on 2023-06-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_voted_president_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='voted_wocom',
            field=models.BooleanField(default=False),
        ),
    ]
