# Generated by Django 4.2.2 on 2023-06-13 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_voted_wocom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='voted_president',
            new_name='president',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='voted_secretary',
            new_name='secretary',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='voted_treasurer',
            new_name='treasurer',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='voted_vice_president',
            new_name='vice_president',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='voted_wocom',
            new_name='wocom',
        ),
    ]
