# Generated by Django 4.2.2 on 2023-06-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_voted_president_customuser_president_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='president',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='secretary',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='treasurer',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='vice_president',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='wocom',
        ),
        migrations.AddField(
            model_name='customuser',
            name='voted',
            field=models.CharField(default='President', max_length=120),
            preserve_default=False,
        ),
    ]
