# Generated by Django 4.2.2 on 2023-06-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_president_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='voted',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
