# Generated by Django 4.2.2 on 2023-06-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='candidate',
            name='num_of_votes',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
