# Generated by Django 4.2.2 on 2023-06-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_category_options_alter_candidate_num_of_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
