# Generated by Django 4.2.2 on 2023-06-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_category_candidate_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='num_of_votes',
            field=models.IntegerField(default=0),
        ),
    ]
